UPDATE_DATA_TO_SESSION_CHAT = """
UPDATE SESSION_CHAT_SQL 
SET RESPONSE_TEXT = ?
WHERE SESSION_ID =? AND CHAT_ID =? AND SOURCE_AGENT=?;
"""

INSERT_SESSION_CHAT_TO_ID = """
INSERT INTO SESSION_CHAT_SQL (SESSION_ID, CHAT_ID , SOURCE_AGENT , PROMPT_TEXT , CREATED_AT)
VALUES (?, ? ,? , ? , GETUTCDATE())
"""

GET_SESSION_CHAT_SQL = """
SELECT * 
FROM SESSION_CHAT_SQL
WHERE (SESSION_ID =?);
"""

INSERT_SESSION_ARTIFACTS_TO_DB = """
INSERT INTO SESSION_ARTIFACTS_SQL (SESSION_ID, CHAT_ID, ARTIFACT_ID, SOURCE_AGENT, TITLE, EXPLANATION,SQL_QUERY)
VALUES (?, ? , ?, ?, ?, ? ,?, GETUTCDATE())
"""